### PR TITLE
Fix/remove mtribe composer util

### PR DESCRIPTION
**Pull request by dpellenwood**
## What does this do/fix?
- Remove Gravity Forms as a composer dependency and the respective mtribe.site composer utility. Gravity Forms should be added directly to a project repo when required.

[Related Slack conversation.](https://tribe.slack.com/archives/C059WEJF9PB/p1696542199114139?thread_ts=1696525529.011279&cid=C059WEJF9PB)

### CODE REVIEW

**Review by JMRhodes — APPROVED** [review]
👍

**Review by jamiepaul — CHANGES_REQUESTED** [review]
🟠 README.md still includes instructions related to the `.env` and Gravity Forms initial setup. We should probably remove those notes as well.

**Comment by MlKilderkin** [comment]
> 🟠 README.md still includes instructions related to the `.env` and Gravity Forms initial setup. We should probably remove those notes as well.

I believe we can also cleanup .env.sample or even delete it at all since we don't need it now

**Review by MlKilderkin — APPROVED** [review]

**Comment by dpellenwood** [comment]
> 🟠 README.md still includes instructions related to the `.env` and Gravity Forms initial setup. We should probably remove those notes as well.

Good catch, @jamiepaul & @MlKilderkin . I went ahead and removed the references to the .env file from the docs as well as the sample and related deployment actions. Give this another look?

**Review by MlKilderkin — APPROVED** [review]

**Review by jamiepaul — APPROVED** [review]
🟢 👍🏻

**Pull request merged**
