### PR TITLE
[MOOSE-51]: Color Names

### PR DESCRIPTION
**Pull request by Vinsanity**
Change primary and secondary color names to the name of the colors.

## What does this do/fix?

The use of `primary` and `secondary` as Brand color names did not fit with all projects.

I did not change the use of Primary and Secondary as a name for button style variations.

## QA

Links to relevant issues
- [Link to Issue](https://moderntribe.atlassian.net/browse/MOOSE-51)

### CODE REVIEW

**Review by jamiepaul — APPROVED** [review]
🟢 👍🏻  thanks for doing this Vinny!

**Review by dpellenwood — APPROVED** [review]
🟣 💨

**Review by GeoffDusome — APPROVED** [review]
🟢 This looks good. Thanks for tackling!

**Review by LayaTaal — APPROVED** [review]
👍

**Comment by dpellenwood** [comment]
@Vinsanity , think you have a couple minutes to merge this one?

**Pull request merged**
