### PR TITLE
Enable linting for GHA workflows.

### PR DESCRIPTION
**Pull request by dpellenwood**
## What does this do/fix?
Adds linting to theme files as part of the GHA workflows.

### CODE REVIEW

**Comment by dpellenwood** [comment]
I'm not sure what your plan was for organizing the theme linting, @ChrisMKindred , but I did get it working on this PR.

**Comment by ChrisMKindred** [comment]
> I'm not sure what your plan was for organizing the theme linting, @ChrisMKindred , but I did get it working on this PR.

Nice!  I think this is fie, PHPCS and JS Linting in one action, then PHPStan, then the testing framework.

**Review by ChrisMKindred — APPROVED** [review]
👍

**Review by jamiepaul — APPROVED** [review]
🟢  works great 👍

**Pull request merged**
